// Code generated by protoc-gen-go. DO NOT EDIT.
// source: githubtasks.proto

package githubtasks

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Milestone_MilestoneState int32

const (
	Milestone_CREATED  Milestone_MilestoneState = 0
	Milestone_IDLE     Milestone_MilestoneState = 1
	Milestone_ACTIVE   Milestone_MilestoneState = 2
	Milestone_COMPLETE Milestone_MilestoneState = 3
)

var Milestone_MilestoneState_name = map[int32]string{
	0: "CREATED",
	1: "IDLE",
	2: "ACTIVE",
	3: "COMPLETE",
}

var Milestone_MilestoneState_value = map[string]int32{
	"CREATED":  0,
	"IDLE":     1,
	"ACTIVE":   2,
	"COMPLETE": 3,
}

func (x Milestone_MilestoneState) String() string {
	return proto.EnumName(Milestone_MilestoneState_name, int32(x))
}

func (Milestone_MilestoneState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{1, 0}
}

type Project struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Milestones           []*Milestone `protobuf:"bytes,2,rep,name=milestones,proto3" json:"milestones,omitempty"`
	GithubProject        string       `protobuf:"bytes,3,opt,name=github_project,json=githubProject,proto3" json:"github_project,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetMilestones() []*Milestone {
	if m != nil {
		return m.Milestones
	}
	return nil
}

func (m *Project) GetGithubProject() string {
	if m != nil {
		return m.GithubProject
	}
	return ""
}

type Milestone struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number               int32                    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	State                Milestone_MilestoneState `protobuf:"varint,3,opt,name=state,proto3,enum=githubtasks.Milestone_MilestoneState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Milestone) Reset()         { *m = Milestone{} }
func (m *Milestone) String() string { return proto.CompactTextString(m) }
func (*Milestone) ProtoMessage()    {}
func (*Milestone) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{1}
}

func (m *Milestone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Milestone.Unmarshal(m, b)
}
func (m *Milestone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Milestone.Marshal(b, m, deterministic)
}
func (m *Milestone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Milestone.Merge(m, src)
}
func (m *Milestone) XXX_Size() int {
	return xxx_messageInfo_Milestone.Size(m)
}
func (m *Milestone) XXX_DiscardUnknown() {
	xxx_messageInfo_Milestone.DiscardUnknown(m)
}

var xxx_messageInfo_Milestone proto.InternalMessageInfo

func (m *Milestone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Milestone) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Milestone) GetState() Milestone_MilestoneState {
	if m != nil {
		return m.State
	}
	return Milestone_CREATED
}

type AddProjectRequest struct {
	Add                  *Project `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectRequest) Reset()         { *m = AddProjectRequest{} }
func (m *AddProjectRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectRequest) ProtoMessage()    {}
func (*AddProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{2}
}

func (m *AddProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectRequest.Unmarshal(m, b)
}
func (m *AddProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectRequest.Merge(m, src)
}
func (m *AddProjectRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectRequest.Size(m)
}
func (m *AddProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectRequest proto.InternalMessageInfo

func (m *AddProjectRequest) GetAdd() *Project {
	if m != nil {
		return m.Add
	}
	return nil
}

type AddProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectResponse) Reset()         { *m = AddProjectResponse{} }
func (m *AddProjectResponse) String() string { return proto.CompactTextString(m) }
func (*AddProjectResponse) ProtoMessage()    {}
func (*AddProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{3}
}

func (m *AddProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectResponse.Unmarshal(m, b)
}
func (m *AddProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectResponse.Marshal(b, m, deterministic)
}
func (m *AddProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectResponse.Merge(m, src)
}
func (m *AddProjectResponse) XXX_Size() int {
	return xxx_messageInfo_AddProjectResponse.Size(m)
}
func (m *AddProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectResponse proto.InternalMessageInfo

type UpdateProjectRequest struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Milestone            *Milestone `protobuf:"bytes,2,opt,name=milestone,proto3" json:"milestone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{4}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectRequest) GetMilestone() *Milestone {
	if m != nil {
		return m.Milestone
	}
	return nil
}

type UpdateProjectResponse struct {
	Updated              *Project `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectResponse) Reset()         { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()    {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{5}
}

func (m *UpdateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResponse.Unmarshal(m, b)
}
func (m *UpdateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResponse.Merge(m, src)
}
func (m *UpdateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResponse.Size(m)
}
func (m *UpdateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResponse proto.InternalMessageInfo

func (m *UpdateProjectResponse) GetUpdated() *Project {
	if m != nil {
		return m.Updated
	}
	return nil
}

func init() {
	proto.RegisterEnum("githubtasks.Milestone_MilestoneState", Milestone_MilestoneState_name, Milestone_MilestoneState_value)
	proto.RegisterType((*Project)(nil), "githubtasks.Project")
	proto.RegisterType((*Milestone)(nil), "githubtasks.Milestone")
	proto.RegisterType((*AddProjectRequest)(nil), "githubtasks.AddProjectRequest")
	proto.RegisterType((*AddProjectResponse)(nil), "githubtasks.AddProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "githubtasks.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "githubtasks.UpdateProjectResponse")
}

func init() { proto.RegisterFile("githubtasks.proto", fileDescriptor_0d888ecb083325cf) }

var fileDescriptor_0d888ecb083325cf = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcb, 0x6e, 0xda, 0x40,
	0x14, 0xc5, 0x98, 0xe7, 0x35, 0x20, 0x73, 0x45, 0x91, 0xc5, 0xa2, 0xa5, 0x23, 0x51, 0xb1, 0x62,
	0xe1, 0x56, 0xdd, 0xb0, 0xb2, 0xc0, 0xaa, 0x90, 0x40, 0x20, 0xe3, 0x56, 0xdd, 0x25, 0x06, 0x8f,
	0x12, 0x92, 0x60, 0x3b, 0x9e, 0x71, 0x56, 0xf9, 0xaf, 0x28, 0x7f, 0x17, 0xe1, 0x07, 0xd8, 0xc4,
	0xb0, 0x1b, 0xcf, 0x79, 0xdc, 0x73, 0x8f, 0x35, 0xd0, 0xbe, 0xdb, 0xf1, 0xfb, 0x60, 0xc3, 0x2d,
	0xf6, 0xc8, 0x46, 0x9e, 0xef, 0x72, 0x17, 0xa5, 0xd4, 0x15, 0x79, 0x85, 0xea, 0xca, 0x77, 0x1f,
	0xe8, 0x96, 0x23, 0x42, 0xc9, 0xb1, 0xf6, 0x54, 0x11, 0xfa, 0xc2, 0xb0, 0x6e, 0x84, 0x67, 0xfc,
	0x0d, 0xb0, 0xdf, 0x3d, 0x51, 0xc6, 0x5d, 0x87, 0x32, 0xa5, 0xd8, 0x17, 0x87, 0x92, 0xda, 0x1d,
	0xa5, 0x3d, 0x17, 0x09, 0x6c, 0xa4, 0x98, 0x38, 0x80, 0x56, 0x44, 0xba, 0xf1, 0x22, 0x77, 0x45,
	0x0c, 0x5d, 0x9b, 0xd1, 0x6d, 0x3c, 0x92, 0xbc, 0x09, 0x50, 0x3f, 0x1a, 0xe4, 0x06, 0xe8, 0x42,
	0xc5, 0x09, 0xf6, 0x1b, 0xea, 0x2b, 0xc5, 0xbe, 0x30, 0x2c, 0x1b, 0xf1, 0x17, 0x8e, 0xa1, 0xcc,
	0xb8, 0xc5, 0x69, 0xe8, 0xdb, 0x52, 0x07, 0xf9, 0x99, 0x4e, 0xa7, 0xf5, 0x81, 0x6c, 0x44, 0x1a,
	0xa2, 0x41, 0x2b, 0x0b, 0xa0, 0x04, 0xd5, 0x89, 0xa1, 0x6b, 0xa6, 0x3e, 0x95, 0x0b, 0x58, 0x83,
	0xd2, 0x6c, 0x3a, 0xd7, 0x65, 0x01, 0x01, 0x2a, 0xda, 0xc4, 0x9c, 0xfd, 0xd3, 0xe5, 0x22, 0x36,
	0xa0, 0x36, 0x59, 0x2e, 0x56, 0x73, 0xdd, 0xd4, 0x65, 0x91, 0x8c, 0xa1, 0xad, 0xd9, 0x76, 0xbc,
	0x87, 0x41, 0x9f, 0x03, 0xca, 0x38, 0xfe, 0x00, 0xd1, 0xb2, 0xed, 0x30, 0xbf, 0xa4, 0x76, 0x32,
	0x91, 0x12, 0xe6, 0x81, 0x40, 0x3a, 0x80, 0x69, 0x31, 0xf3, 0x5c, 0x87, 0x51, 0x72, 0x0b, 0x9d,
	0xbf, 0x9e, 0x6d, 0x71, 0x7a, 0xe6, 0x9a, 0x57, 0xcb, 0x2f, 0xa8, 0x1f, 0xdb, 0x0e, 0x9b, 0xb9,
	0xfc, 0x5b, 0x4e, 0x44, 0xf2, 0x07, 0xbe, 0x9c, 0x4d, 0x88, 0x46, 0xe3, 0x08, 0xaa, 0x41, 0x08,
	0x5c, 0x0f, 0x9f, 0x90, 0xd4, 0x77, 0x01, 0x1a, 0xe6, 0x01, 0x5a, 0x53, 0xff, 0x65, 0xb7, 0xa5,
	0xb8, 0x04, 0x38, 0x6d, 0x84, 0x5f, 0x33, 0xea, 0x4f, 0x3d, 0xf5, 0xbe, 0x5d, 0xc4, 0xe3, 0x2a,
	0x0a, 0xf8, 0x1f, 0x9a, 0x99, 0xa8, 0xf8, 0x3d, 0xa3, 0xc9, 0x2b, 0xaa, 0x47, 0xae, 0x51, 0x12,
	0xe7, 0x4d, 0x25, 0x7c, 0x05, 0x3f, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x66, 0x1f, 0x22,
	0x1a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TasksServiceClient is the client API for TasksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TasksServiceClient interface {
	AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error)
}

type tasksServiceClient struct {
	cc *grpc.ClientConn
}

func NewTasksServiceClient(cc *grpc.ClientConn) TasksServiceClient {
	return &tasksServiceClient{cc}
}

func (c *tasksServiceClient) AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error) {
	out := new(AddProjectResponse)
	err := c.cc.Invoke(ctx, "/githubtasks.TasksService/AddProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error) {
	out := new(UpdateProjectResponse)
	err := c.cc.Invoke(ctx, "/githubtasks.TasksService/UpdateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServiceServer is the server API for TasksService service.
type TasksServiceServer interface {
	AddProject(context.Context, *AddProjectRequest) (*AddProjectResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error)
}

func RegisterTasksServiceServer(s *grpc.Server, srv TasksServiceServer) {
	s.RegisterService(&_TasksService_serviceDesc, srv)
}

func _TasksService_AddProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).AddProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubtasks.TasksService/AddProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).AddProject(ctx, req.(*AddProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubtasks.TasksService/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TasksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "githubtasks.TasksService",
	HandlerType: (*TasksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProject",
			Handler:    _TasksService_AddProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _TasksService_UpdateProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "githubtasks.proto",
}
