// Code generated by protoc-gen-go. DO NOT EDIT.
// source: githubtasks.proto

package githubtasks

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Milestone_MilestoneState int32

const (
	Milestone_CREATED  Milestone_MilestoneState = 0
	Milestone_IDLE     Milestone_MilestoneState = 1
	Milestone_ACTIVE   Milestone_MilestoneState = 2
	Milestone_COMPLETE Milestone_MilestoneState = 3
)

var Milestone_MilestoneState_name = map[int32]string{
	0: "CREATED",
	1: "IDLE",
	2: "ACTIVE",
	3: "COMPLETE",
}

var Milestone_MilestoneState_value = map[string]int32{
	"CREATED":  0,
	"IDLE":     1,
	"ACTIVE":   2,
	"COMPLETE": 3,
}

func (x Milestone_MilestoneState) String() string {
	return proto.EnumName(Milestone_MilestoneState_name, int32(x))
}

func (Milestone_MilestoneState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{2, 0}
}

type Task_TaskState int32

const (
	Task_CREATED  Task_TaskState = 0
	Task_IDLE     Task_TaskState = 1
	Task_ACTIVE   Task_TaskState = 2
	Task_COMPLETE Task_TaskState = 3
)

var Task_TaskState_name = map[int32]string{
	0: "CREATED",
	1: "IDLE",
	2: "ACTIVE",
	3: "COMPLETE",
}

var Task_TaskState_value = map[string]int32{
	"CREATED":  0,
	"IDLE":     1,
	"ACTIVE":   2,
	"COMPLETE": 3,
}

func (x Task_TaskState) String() string {
	return proto.EnumName(Task_TaskState_name, int32(x))
}

func (Task_TaskState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{3, 0}
}

type Config struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	LastUpdate           int64      `protobuf:"varint,2,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *Config) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

type Project struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Milestones           []*Milestone `protobuf:"bytes,2,rep,name=milestones,proto3" json:"milestones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{1}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetMilestones() []*Milestone {
	if m != nil {
		return m.Milestones
	}
	return nil
}

type Milestone struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number               int32                    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	State                Milestone_MilestoneState `protobuf:"varint,3,opt,name=state,proto3,enum=githubtasks.Milestone_MilestoneState" json:"state,omitempty"`
	Tasks                []*Task                  `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	GithubProject        string                   `protobuf:"bytes,5,opt,name=github_project,json=githubProject,proto3" json:"github_project,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Milestone) Reset()         { *m = Milestone{} }
func (m *Milestone) String() string { return proto.CompactTextString(m) }
func (*Milestone) ProtoMessage()    {}
func (*Milestone) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{2}
}

func (m *Milestone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Milestone.Unmarshal(m, b)
}
func (m *Milestone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Milestone.Marshal(b, m, deterministic)
}
func (m *Milestone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Milestone.Merge(m, src)
}
func (m *Milestone) XXX_Size() int {
	return xxx_messageInfo_Milestone.Size(m)
}
func (m *Milestone) XXX_DiscardUnknown() {
	xxx_messageInfo_Milestone.DiscardUnknown(m)
}

var xxx_messageInfo_Milestone proto.InternalMessageInfo

func (m *Milestone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Milestone) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Milestone) GetState() Milestone_MilestoneState {
	if m != nil {
		return m.State
	}
	return Milestone_CREATED
}

func (m *Milestone) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *Milestone) GetGithubProject() string {
	if m != nil {
		return m.GithubProject
	}
	return ""
}

type Task struct {
	Title                string         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string         `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	State                Task_TaskState `protobuf:"varint,4,opt,name=state,proto3,enum=githubtasks.Task_TaskState" json:"state,omitempty"`
	Number               int32          `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	Uid                  int64          `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{3}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Task) GetState() Task_TaskState {
	if m != nil {
		return m.State
	}
	return Task_CREATED
}

func (m *Task) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Task) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type AddProjectRequest struct {
	Add                  *Project `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectRequest) Reset()         { *m = AddProjectRequest{} }
func (m *AddProjectRequest) String() string { return proto.CompactTextString(m) }
func (*AddProjectRequest) ProtoMessage()    {}
func (*AddProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{4}
}

func (m *AddProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectRequest.Unmarshal(m, b)
}
func (m *AddProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectRequest.Marshal(b, m, deterministic)
}
func (m *AddProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectRequest.Merge(m, src)
}
func (m *AddProjectRequest) XXX_Size() int {
	return xxx_messageInfo_AddProjectRequest.Size(m)
}
func (m *AddProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectRequest proto.InternalMessageInfo

func (m *AddProjectRequest) GetAdd() *Project {
	if m != nil {
		return m.Add
	}
	return nil
}

type AddProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProjectResponse) Reset()         { *m = AddProjectResponse{} }
func (m *AddProjectResponse) String() string { return proto.CompactTextString(m) }
func (*AddProjectResponse) ProtoMessage()    {}
func (*AddProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{5}
}

func (m *AddProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProjectResponse.Unmarshal(m, b)
}
func (m *AddProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProjectResponse.Marshal(b, m, deterministic)
}
func (m *AddProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProjectResponse.Merge(m, src)
}
func (m *AddProjectResponse) XXX_Size() int {
	return xxx_messageInfo_AddProjectResponse.Size(m)
}
func (m *AddProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProjectResponse proto.InternalMessageInfo

type UpdateProjectRequest struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Milestone            *Milestone `protobuf:"bytes,2,opt,name=milestone,proto3" json:"milestone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{6}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectRequest) GetMilestone() *Milestone {
	if m != nil {
		return m.Milestone
	}
	return nil
}

type UpdateProjectResponse struct {
	Updated              *Project `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectResponse) Reset()         { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()    {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{7}
}

func (m *UpdateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResponse.Unmarshal(m, b)
}
func (m *UpdateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResponse.Merge(m, src)
}
func (m *UpdateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResponse.Size(m)
}
func (m *UpdateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResponse proto.InternalMessageInfo

func (m *UpdateProjectResponse) GetUpdated() *Project {
	if m != nil {
		return m.Updated
	}
	return nil
}

type AddTaskRequest struct {
	MilestoneName        string   `protobuf:"bytes,1,opt,name=milestone_name,json=milestoneName,proto3" json:"milestone_name,omitempty"`
	MilestoneNumber      int32    `protobuf:"varint,2,opt,name=milestone_number,json=milestoneNumber,proto3" json:"milestone_number,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskRequest) Reset()         { *m = AddTaskRequest{} }
func (m *AddTaskRequest) String() string { return proto.CompactTextString(m) }
func (*AddTaskRequest) ProtoMessage()    {}
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{8}
}

func (m *AddTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskRequest.Unmarshal(m, b)
}
func (m *AddTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskRequest.Marshal(b, m, deterministic)
}
func (m *AddTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskRequest.Merge(m, src)
}
func (m *AddTaskRequest) XXX_Size() int {
	return xxx_messageInfo_AddTaskRequest.Size(m)
}
func (m *AddTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskRequest proto.InternalMessageInfo

func (m *AddTaskRequest) GetMilestoneName() string {
	if m != nil {
		return m.MilestoneName
	}
	return ""
}

func (m *AddTaskRequest) GetMilestoneNumber() int32 {
	if m != nil {
		return m.MilestoneNumber
	}
	return 0
}

func (m *AddTaskRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddTaskRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type AddTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTaskResponse) Reset()         { *m = AddTaskResponse{} }
func (m *AddTaskResponse) String() string { return proto.CompactTextString(m) }
func (*AddTaskResponse) ProtoMessage()    {}
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{9}
}

func (m *AddTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTaskResponse.Unmarshal(m, b)
}
func (m *AddTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTaskResponse.Marshal(b, m, deterministic)
}
func (m *AddTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTaskResponse.Merge(m, src)
}
func (m *AddTaskResponse) XXX_Size() int {
	return xxx_messageInfo_AddTaskResponse.Size(m)
}
func (m *AddTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTaskResponse proto.InternalMessageInfo

func (m *AddTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type GetMilestonesRequest struct {
	GithubProject        string   `protobuf:"bytes,1,opt,name=github_project,json=githubProject,proto3" json:"github_project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMilestonesRequest) Reset()         { *m = GetMilestonesRequest{} }
func (m *GetMilestonesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMilestonesRequest) ProtoMessage()    {}
func (*GetMilestonesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{10}
}

func (m *GetMilestonesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMilestonesRequest.Unmarshal(m, b)
}
func (m *GetMilestonesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMilestonesRequest.Marshal(b, m, deterministic)
}
func (m *GetMilestonesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMilestonesRequest.Merge(m, src)
}
func (m *GetMilestonesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMilestonesRequest.Size(m)
}
func (m *GetMilestonesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMilestonesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMilestonesRequest proto.InternalMessageInfo

func (m *GetMilestonesRequest) GetGithubProject() string {
	if m != nil {
		return m.GithubProject
	}
	return ""
}

type GetMilestonesResponse struct {
	Milestones           []*Milestone `protobuf:"bytes,1,rep,name=milestones,proto3" json:"milestones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMilestonesResponse) Reset()         { *m = GetMilestonesResponse{} }
func (m *GetMilestonesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMilestonesResponse) ProtoMessage()    {}
func (*GetMilestonesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{11}
}

func (m *GetMilestonesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMilestonesResponse.Unmarshal(m, b)
}
func (m *GetMilestonesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMilestonesResponse.Marshal(b, m, deterministic)
}
func (m *GetMilestonesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMilestonesResponse.Merge(m, src)
}
func (m *GetMilestonesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMilestonesResponse.Size(m)
}
func (m *GetMilestonesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMilestonesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMilestonesResponse proto.InternalMessageInfo

func (m *GetMilestonesResponse) GetMilestones() []*Milestone {
	if m != nil {
		return m.Milestones
	}
	return nil
}

type GetProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{12}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

type GetProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProjectsResponse) Reset()         { *m = GetProjectsResponse{} }
func (m *GetProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectsResponse) ProtoMessage()    {}
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d888ecb083325cf, []int{13}
}

func (m *GetProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsResponse.Unmarshal(m, b)
}
func (m *GetProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsResponse.Merge(m, src)
}
func (m *GetProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectsResponse.Size(m)
}
func (m *GetProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsResponse proto.InternalMessageInfo

func (m *GetProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterEnum("githubtasks.Milestone_MilestoneState", Milestone_MilestoneState_name, Milestone_MilestoneState_value)
	proto.RegisterEnum("githubtasks.Task_TaskState", Task_TaskState_name, Task_TaskState_value)
	proto.RegisterType((*Config)(nil), "githubtasks.config")
	proto.RegisterType((*Project)(nil), "githubtasks.Project")
	proto.RegisterType((*Milestone)(nil), "githubtasks.Milestone")
	proto.RegisterType((*Task)(nil), "githubtasks.Task")
	proto.RegisterType((*AddProjectRequest)(nil), "githubtasks.AddProjectRequest")
	proto.RegisterType((*AddProjectResponse)(nil), "githubtasks.AddProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "githubtasks.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "githubtasks.UpdateProjectResponse")
	proto.RegisterType((*AddTaskRequest)(nil), "githubtasks.AddTaskRequest")
	proto.RegisterType((*AddTaskResponse)(nil), "githubtasks.AddTaskResponse")
	proto.RegisterType((*GetMilestonesRequest)(nil), "githubtasks.GetMilestonesRequest")
	proto.RegisterType((*GetMilestonesResponse)(nil), "githubtasks.GetMilestonesResponse")
	proto.RegisterType((*GetProjectsRequest)(nil), "githubtasks.GetProjectsRequest")
	proto.RegisterType((*GetProjectsResponse)(nil), "githubtasks.GetProjectsResponse")
}

func init() { proto.RegisterFile("githubtasks.proto", fileDescriptor_0d888ecb083325cf) }

var fileDescriptor_0d888ecb083325cf = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xad, 0x63, 0x3b, 0x69, 0x6e, 0xda, 0xd4, 0xbd, 0x9f, 0x5b, 0x59, 0xe9, 0x27, 0x1a, 0x46,
	0x0a, 0x84, 0x4d, 0x05, 0x05, 0x21, 0xa4, 0xc2, 0x22, 0x6a, 0x4d, 0x54, 0xa9, 0xa5, 0x95, 0x9b,
	0x22, 0x24, 0x16, 0xc5, 0xa9, 0x87, 0x62, 0x9a, 0xc4, 0x21, 0x33, 0x41, 0xe2, 0x09, 0xd8, 0xf0,
	0x66, 0xac, 0x79, 0x1f, 0xe4, 0xf1, 0xf8, 0x37, 0x4e, 0x45, 0x37, 0xd1, 0xf8, 0xfe, 0x9d, 0x73,
	0xcf, 0x1c, 0x3b, 0xb0, 0x79, 0xe3, 0xf3, 0x2f, 0xf3, 0x21, 0x77, 0xd9, 0x2d, 0xdb, 0x9b, 0xce,
	0x02, 0x1e, 0x60, 0x23, 0x13, 0x22, 0x1f, 0xa1, 0x7a, 0x1d, 0x4c, 0x3e, 0xfb, 0x37, 0xf8, 0x14,
	0x56, 0xa7, 0xb3, 0xe0, 0x2b, 0xbd, 0xe6, 0xcc, 0x52, 0xda, 0x6a, 0xb7, 0xb1, 0x6f, 0xee, 0x65,
	0x9b, 0xcf, 0xa3, 0xa4, 0x93, 0x54, 0xe1, 0x2e, 0x34, 0x46, 0x2e, 0xe3, 0x57, 0xf3, 0xa9, 0xe7,
	0x72, 0x6a, 0x55, 0xda, 0x4a, 0x57, 0x75, 0x20, 0x0c, 0x5d, 0x8a, 0x08, 0xb9, 0x84, 0x9a, 0xec,
	0x42, 0x04, 0x6d, 0xe2, 0x8e, 0xa9, 0xa5, 0xb4, 0x95, 0x6e, 0xdd, 0x11, 0x67, 0x7c, 0x09, 0x30,
	0xf6, 0x47, 0x94, 0xf1, 0x60, 0x42, 0x99, 0x55, 0x11, 0x98, 0xdb, 0x39, 0xcc, 0xd3, 0x38, 0xed,
	0x64, 0x2a, 0xc9, 0xcf, 0x0a, 0xd4, 0x93, 0x4c, 0xe9, 0xe4, 0x6d, 0xa8, 0x4e, 0xe6, 0xe3, 0x21,
	0x9d, 0x09, 0x52, 0xba, 0x23, 0x9f, 0xf0, 0x00, 0x74, 0xc6, 0x43, 0xae, 0x6a, 0x5b, 0xe9, 0x36,
	0xf7, 0x3b, 0xe5, 0x60, 0xe9, 0xe9, 0x22, 0x2c, 0x76, 0xa2, 0x1e, 0x7c, 0x0c, 0xba, 0x28, 0xb4,
	0x34, 0xc1, 0x74, 0x33, 0xd7, 0x3c, 0x70, 0xd9, 0xad, 0x13, 0xe5, 0xb1, 0x03, 0xcd, 0x28, 0x75,
	0x25, 0xa5, 0xb2, 0x74, 0xc1, 0x6d, 0x3d, 0x8a, 0x4a, 0x49, 0x48, 0x0f, 0x9a, 0x79, 0x20, 0x6c,
	0x40, 0xed, 0xd0, 0xb1, 0x7b, 0x03, 0xfb, 0xc8, 0x58, 0xc1, 0x55, 0xd0, 0x8e, 0x8f, 0x4e, 0x6c,
	0x43, 0x41, 0x80, 0x6a, 0xef, 0x70, 0x70, 0xfc, 0xde, 0x36, 0x2a, 0xb8, 0x06, 0xab, 0x87, 0x67,
	0xa7, 0xe7, 0x27, 0xf6, 0xc0, 0x36, 0x54, 0xf2, 0x5b, 0x01, 0x2d, 0x44, 0x46, 0x13, 0x74, 0xee,
	0xf3, 0x51, 0xac, 0x42, 0xf4, 0x10, 0x4a, 0x33, 0x0c, 0xbc, 0x1f, 0x42, 0x84, 0xba, 0x23, 0xce,
	0xf8, 0x2c, 0x96, 0x40, 0x13, 0x12, 0xec, 0x2c, 0x6c, 0x21, 0x7e, 0x72, 0x8b, 0xa7, 0x6a, 0xea,
	0x39, 0x35, 0x0d, 0x50, 0xe7, 0xbe, 0x67, 0x55, 0xc5, 0xbd, 0x87, 0x47, 0xf2, 0x1a, 0xea, 0x49,
	0xf7, 0xfd, 0xb7, 0x39, 0x80, 0xcd, 0x9e, 0xe7, 0xc5, 0x3e, 0xa3, 0xdf, 0xe6, 0x94, 0x71, 0x7c,
	0x04, 0xaa, 0xeb, 0x79, 0x62, 0xaf, 0x65, 0x8e, 0x0c, 0x0b, 0x88, 0x09, 0x98, 0x6d, 0x66, 0xd3,
	0x60, 0xc2, 0x28, 0xf9, 0x04, 0x66, 0xe4, 0xc5, 0xc2, 0xd4, 0x32, 0xd3, 0xbc, 0x80, 0x7a, 0x62,
	0x32, 0x21, 0xd9, 0x72, 0x37, 0xa6, 0x85, 0xa4, 0x0f, 0x5b, 0x05, 0x84, 0x08, 0x1a, 0xf7, 0xa0,
	0x16, 0xbd, 0x18, 0x77, 0x93, 0x8f, 0x8b, 0xc8, 0x2f, 0x05, 0x9a, 0x3d, 0xcf, 0x13, 0x46, 0x92,
	0x2c, 0x3b, 0xd0, 0x4c, 0x80, 0xae, 0x32, 0x7c, 0xd7, 0x93, 0xe8, 0xbb, 0x90, 0xf8, 0x13, 0x30,
	0x32, 0x65, 0x59, 0xdf, 0x6f, 0xa4, 0x85, 0xd1, 0x95, 0x25, 0x3e, 0x51, 0xcb, 0x7c, 0xa2, 0xa5,
	0x3e, 0x21, 0xaf, 0x60, 0x23, 0x61, 0x23, 0x37, 0xea, 0x80, 0x16, 0x72, 0x97, 0xeb, 0x94, 0xf8,
	0x5f, 0xa4, 0xc9, 0x1b, 0x30, 0xfb, 0x94, 0x27, 0x62, 0xb1, 0xcc, 0x36, 0x85, 0xd7, 0x42, 0x29,
	0x7b, 0x2d, 0xce, 0x60, 0xab, 0xd0, 0x2e, 0xe1, 0xf3, 0x9f, 0x0b, 0xe5, 0x9f, 0x3f, 0x17, 0x26,
	0x60, 0x9f, 0x72, 0x39, 0x3e, 0x66, 0x43, 0xfa, 0xf0, 0x5f, 0x2e, 0x2a, 0x41, 0xee, 0xfd, 0x15,
	0xdc, 0xff, 0x53, 0x81, 0xb5, 0x70, 0x7b, 0x76, 0x41, 0x67, 0xdf, 0xfd, 0x6b, 0x8a, 0x67, 0x00,
	0xa9, 0x13, 0xf1, 0x41, 0xae, 0x7d, 0xc1, 0xdf, 0xad, 0xdd, 0xa5, 0x79, 0x69, 0xe1, 0x15, 0x74,
	0xa0, 0x91, 0xa1, 0x8a, 0xf9, 0x8e, 0xc5, 0xd5, 0x5a, 0xed, 0xe5, 0x05, 0xc9, 0xcc, 0xb7, 0x50,
	0x93, 0xd7, 0x8b, 0x3b, 0x45, 0x06, 0x19, 0x0b, 0xb6, 0xfe, 0x2f, 0x4f, 0x26, 0x73, 0x3e, 0xc0,
	0x7a, 0xee, 0xb6, 0xf0, 0x61, 0x11, 0x7c, 0xc1, 0x08, 0x2d, 0x72, 0x57, 0x49, 0x3c, 0x79, 0x58,
	0x15, 0xff, 0x56, 0xcf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x08, 0x4e, 0x9f, 0xc2, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TasksServiceClient is the client API for TasksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TasksServiceClient interface {
	AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	//rpc UpdateProject(UpdateProjectRequest) returns (UpdateProjectResponse) {};
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error)
	GetMilestones(ctx context.Context, in *GetMilestonesRequest, opts ...grpc.CallOption) (*GetMilestonesResponse, error)
}

type tasksServiceClient struct {
	cc *grpc.ClientConn
}

func NewTasksServiceClient(cc *grpc.ClientConn) TasksServiceClient {
	return &tasksServiceClient{cc}
}

func (c *tasksServiceClient) AddProject(ctx context.Context, in *AddProjectRequest, opts ...grpc.CallOption) (*AddProjectResponse, error) {
	out := new(AddProjectResponse)
	err := c.cc.Invoke(ctx, "/githubtasks.TasksService/AddProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, "/githubtasks.TasksService/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error) {
	out := new(AddTaskResponse)
	err := c.cc.Invoke(ctx, "/githubtasks.TasksService/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tasksServiceClient) GetMilestones(ctx context.Context, in *GetMilestonesRequest, opts ...grpc.CallOption) (*GetMilestonesResponse, error) {
	out := new(GetMilestonesResponse)
	err := c.cc.Invoke(ctx, "/githubtasks.TasksService/GetMilestones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TasksServiceServer is the server API for TasksService service.
type TasksServiceServer interface {
	AddProject(context.Context, *AddProjectRequest) (*AddProjectResponse, error)
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	//rpc UpdateProject(UpdateProjectRequest) returns (UpdateProjectResponse) {};
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	GetMilestones(context.Context, *GetMilestonesRequest) (*GetMilestonesResponse, error)
}

func RegisterTasksServiceServer(s *grpc.Server, srv TasksServiceServer) {
	s.RegisterService(&_TasksService_serviceDesc, srv)
}

func _TasksService_AddProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).AddProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubtasks.TasksService/AddProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).AddProject(ctx, req.(*AddProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubtasks.TasksService/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubtasks.TasksService/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TasksService_GetMilestones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMilestonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TasksServiceServer).GetMilestones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/githubtasks.TasksService/GetMilestones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TasksServiceServer).GetMilestones(ctx, req.(*GetMilestonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TasksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "githubtasks.TasksService",
	HandlerType: (*TasksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProject",
			Handler:    _TasksService_AddProject_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _TasksService_GetProjects_Handler,
		},
		{
			MethodName: "AddTask",
			Handler:    _TasksService_AddTask_Handler,
		},
		{
			MethodName: "GetMilestones",
			Handler:    _TasksService_GetMilestones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "githubtasks.proto",
}
